import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  BankOutline,
  HomeOutline,
  UserOutline,
  WalletOutline,
  SwapOutline,
  ArrowUpOutline,
  ArrowDownOutline,
  DownloadOutline,
  LeftOutline,
  ClockCircleOutline,
  ExclamationCircleOutline,
  CheckCircleOutline,
  LineChartOutline,
  DownOutline,
  LogoutOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  BankOutline,
  HomeOutline,
  UserOutline,
  WalletOutline,
  SwapOutline,
  ArrowUpOutline,
  ArrowDownOutline,
  DownloadOutline,
  LeftOutline,
  ClockCircleOutline,
  ExclamationCircleOutline,
  CheckCircleOutline,
  LineChartOutline,
  DownOutline,
  LogoutOutline,
];
